In [2]:
import pandas as pd
import requests 
from bs4 import BeautifulSoup

In [3]:
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?page=1', headers = headers).text

In [4]:
soup = BeautifulSoup(webpage, 'lxml')

In [28]:
company = soup.find_all('div', class_='companyCardWrapper')

In [29]:
len(company)

20

In [60]:
name = []
rating = []
review = []
salaries = []
interviews = []
jobs = []
ctype_and_location = []
for i in company:
    name.append(i.find('h2', class_='companyCardWrapper__companyName').text.strip())
    rating.append(i.find('div', class_='rating_text rating_text--md').text.strip()) 
    review.append(i.find('span', class_='companyCardWrapper__companyRatingCount').text.strip())
    action_counts = i.find_all('span', class_='companyCardWrapper__ActionCount')

    salaries.append(action_counts[0].text.strip())
    interviews.append(action_counts[1].text.strip())
    jobs.append(action_counts[2].text.strip())
    ctype_and_location.append(i.find('span', class_='companyCardWrapper__interLinking').text.strip())

    d={'name':name, 'rating':rating, 'review':review, 'salaries':salaries, 'interviews':interviews, 'jobs':jobs, 'ctype_and_location': ctype_and_location}
    df = pd.DataFrame(d)
    df

In [61]:
df

,name,rating,review,salaries,interviews,jobs,ctype_and_location
0,TCS,3.3,(1.1L),1.1L,10L,11.8k,IT Services & Consulting | Bengaluru +440 othe...
1,Accenture,3.7,(72.7k),72.7k,6.6L,9.3k,IT Services & Consulting | Bengaluru +257 othe...
2,Wipro,3.6,(64.6k),64.6k,4.8L,6.8k,IT Services & Consulting | Hyderabad +371 othe...
3,Cognizant,3.7,(60.9k),60.9k,6L,6.4k,IT Services & Consulting | Hyderabad +234 othe...
4,Capgemini,3.7,(52.6k),52.6k,4.8L,5.5k,IT Services & Consulting | Bengaluru +182 othe...
5,HDFC Bank,3.8,(51.7k),51.7k,1.5L,3k,Banking | Mumbai +1840 other locations
6,Infosys,3.5,(48.3k),48.3k,5.2L,8.4k,IT Services & Consulting | Bengaluru +248 othe...
7,ICICI Bank,4.0,(45.5k),45.5k,1.5L,2.9k,Banking | Mumbai +1441 other locations
8,HCLTech,3.4,(45.5k),45.5k,3.9L,4.5k,IT Services & Consulting | Chennai +233 other ...
9,Tech Mahindra,3.4,(43k),43k,2.8L,4.5k,IT Services & Consulting | Hyderabad +330 othe...
10,Genpact,3.6,(41.7k),41.7k,2.3L,3.9k,Analytics & KPO | Hyderabad +182 other locations
11,TP,3.8,(37.8k),37.8k,97.8k,2.2k,BPO | Mumbai +257 other locations
12,Jio,4.4,(33.5k),33.5k,62.1k,4.4k,Telecom | Mumbai +1961 other locations
13,Axis Bank,3.6,(32.8k),32.8k,1L,1.9k,Banking | Mumbai +1514 other locations
14,Concentrix Corporation,3.6,(31.9k),31.9k,1.3L,2k,BPO | Bengaluru +179 other locations
15,Amazon,3.9,(31.3k),31.3k,1.5L,5.9k,Internet | Bengaluru +524 other locations
16,Reliance Retail,3.9,(27.2k),27.2k,77.1k,1.9k,Retail | Mumbai +1157 other locations
17,iEnergizer,4.6,(27.2k),27.2k,24.5k,1.4k,BPO | Noida +52 other locations
18,LTIMindtree,3.6,(26.2k),26.2k,2L,3.4k,IT Services & Consulting | Bengaluru +145 othe...
19,IBM,3.9,(25.6k),25.6k,2.2L,2.6k,IT Services & Consulting | Bengaluru +161 othe...

In [75]:
final = pd.DataFrame()
for j in range(1,350):
    url = 'https://www.ambitionbox.com/list-of-companies?page={}'.format(j)
    
    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'}
    webpage = requests.get(url, headers = headers).text

    soup = BeautifulSoup(webpage, 'lxml')
    
    company = soup.find_all('div', class_='companyCardWrapper')

    name = []
    rating = []
    review = []
    salaries = []
    interviews = []
    jobs = []
    ctype_and_location = []
    for i in company:
        name.append(i.find('h2', class_='companyCardWrapper__companyName').text.strip())
        rating.append(i.find('div', class_='rating_text rating_text--md').text.strip()) 
        review.append(i.find('span', class_='companyCardWrapper__companyRatingCount').text.strip())
        action_counts = i.find_all('span', class_='companyCardWrapper__ActionCount')
    
        salaries.append(action_counts[0].text.strip())
        interviews.append(action_counts[1].text.strip())
        jobs.append(action_counts[2].text.strip())
        ctype_and_location.append(i.find('span', class_='companyCardWrapper__interLinking').text.strip())
    
        d={'name':name, 'rating':rating, 'review':review, 'salaries':salaries, 'interviews':interviews, 'jobs':jobs, 'ctype_and_location': ctype_and_location}
        df = pd.DataFrame(d)
        final=pd.concat([final, df], ignore_index=True)

final

AttributeError: 'NoneType' object has no attribute 'text'

In [81]:
final.info()

<class 'pandas.DataFrame'>
RangeIndex: 21906 entries, 0 to 21905
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                21906 non-null  str
 1   rating              21906 non-null  str
 2   review              21906 non-null  str
 3   salaries            21906 non-null  str
 4   interviews          21906 non-null  str
 5   jobs                21906 non-null  str
 6   ctype_and_location  21906 non-null  str
dtypes: str(7)
memory usage: 1.2 MB

In [82]:
final

,name,rating,review,salaries,interviews,jobs,ctype_and_location
0,TCS,3.3,(1.1L),1.1L,10L,11.8k,IT Services & Consulting | Bengaluru +440 othe...
1,TCS,3.3,(1.1L),1.1L,10L,11.8k,IT Services & Consulting | Bengaluru +440 othe...
2,Accenture,3.7,(72.7k),72.7k,6.6L,9.3k,IT Services & Consulting | Bengaluru +257 othe...
3,TCS,3.3,(1.1L),1.1L,10L,11.8k,IT Services & Consulting | Bengaluru +440 othe...
4,Accenture,3.7,(72.7k),72.7k,6.6L,9.3k,IT Services & Consulting | Bengaluru +257 othe...
...,...,...,...,...,...,...,...
21901,Spectrum Talent Management,3.6,(518),518,2.1k,36,Recruitment | Noida +86 other locations
21902,OutworX,3.5,(518),518,2.2k,35,IT Services & Consulting | Pune +40 other loca...
21903,Metalman Auto,3.9,(518),518,1.9k,24,Auto Components | Chhatrapati Sambhajinagar +2...
21904,Morepen Laboratories,3.9,(517),517,1.9k,24,Pharma | New Delhi +48 other locations
21905,Mobikwik,3.5,(517),517,2.5k,61,FinTech | Gurugram +49 other locations

In [83]:
final.to_csv('company_data')